server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://casino-db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: identity
  flyway:
    enabled: true
    baselineOnMigrate: true
    createSchemas: true
    schemas: identity
    table: flyway_identity_history

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
