server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: ledger

  flyway:
    enabled: true
    baselineOnMigrate: true
    createSchemas: true
    schemas: ledger
    table: flyway_ledger_history

tron:
  grid:
    api:
      key: ${TRONGRID_API_KEY}
      url: ${TRONGRID_API_URL}
  scan:
    api:
      key: ${TRONSCAN_API_KEY}
      url: ${TRONSCAN_API_URL}

solana:
  helius:
    api:
      url: ${SOLANA_HELIUS_API_URL}
  tokenlist:
    url: ${SOLANA_TOKENLIST_URL}  

  eth:
  infura:
    rpc:
      url: ${ETH_INFURA_RPC_URL}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG