server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: ledger

  flyway:
    enabled: true
    baselineOnMigrate: true
    createSchemas: true
    schemas: ledger
    table: flyway_ledger_history

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
