server:
  port: 8080

spring:
  application:
    name: trader-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth:8081/.well-known/jwks.json

  cloud:
    gateway:
      routes:
        # Auth service (login, refresh, logout)
        - id: auth
          uri: http://auth:8081
          predicates:
            - Path=/api/auth/**
          
        # API service (trader, public, admin)
        - id: api
          uri: http://api:8084
          predicates:
            - Path=/api/trader/**, /api/public/**, /api/admin/**
    
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG
    org.springframework.cloud.gateway.handler.predicate: TRACE